### ISSUE TITLE
Multi-user overwrite protection

### ISSUE THREAD

**Issue by DanielHeath** [schollz/cowyo#107]
Because any keypress causes a save (even if the document hasn't changed), leaving a wiki page open can cause you to overwrite someone elses work when you return to your computer.

If we sent an `if-modified-since` header when saving, the server could detect we're out of date and tell the page JS to block further edits.

**Comment by schollz** [comment]
I see - so the idea is that the time is too long (> 10 minutes?) then it won't allow an edit? I think this is good.

**Comment by DanielHeath** [comment]
That would work. Or compare the time the page loaded with the time it was last modified (to see if it’s been changed by someone else). That way long lived tabs would still be useful.

A bigger job would be to use web sockets to get updated when someone else edits.

Thanks,
Daniel Heath

**Comment by schollz** [comment]
I actually had websockets in the previous version of cowyo. I abandoned them because I never got the lost-connection logic correctly. If a websocket broke (like you moved from one wifi to another) it wouldn't update anymore. The REST methods are a little dumber but they are nice because they don't care if their are network interruptions.

I think comparing the load time and last modification time is a good idea in the meantime. There might be a better way to do websockets nowadays, but I'm not sure.
