### ISSUE TITLE
Error after running the program, the page is automatically refreshed

### ISSUE THREAD

**Issue by onenewnet** [schollz/cowyo#56]
Error after running the program, the page is automatically refreshed

**Comment by schollz** [comment]
Can you make sure the websockets are connecting? Watch the console when Cowyo loads.

Cowyo will automatically restart if the websockets fail (which usually should occur if the internet goes out). However, in your case it might be a problem with Caddy 0.9, which [did not work with websockets correctly](https://github.com/mholt/caddy/issues/886), however this issue is fixed in the master branch (which you can pull with `go get -u github.com/mholt/caddy`).

**Comment by onenewnet** [comment]
Perfect, thank you
