### ISSUE TITLE
Syntax --port :8003 no longer accepted

### ISSUE THREAD

**Issue by petrm** [schollz/cowyo#64]
When I try to start the server with --port :8003, it silently dies. The application is now expecting --port 8003, which unfortunately results in listening only on the default interface.
Using --port 0.0.0.0:8003 also doesn't work. I would like cowyo to listen on all available interfaces.

**Comment by schollz** [comment]
Sorry again for the confusion.

cowyo [does listen on all interfaces](https://github.com/schollz/cowyo/blob/master/handlers.go#L35). When you run `cowyo -p 8003` it prints out

```
Running cowyo server (version X) at http://192.168.X.Y:8003
```

but it is actually listening on `0.0.0.0:8003`. I'll change this. I wanted to printout the local IP so that it can be easily used for LAN networks (without having to look up your local IP).
