### ISSUE TITLE
Is this project basically finished?

### ISSUE THREAD

**Issue by hugows** [schollz/cowyo#82]
I'd love to use something like this for my personal notes, but I miss a few features. I wanted to understand if you are basically happy with the project, or if you plan to continue including more features in the future (in other words, should I fork or should I do pull requests?)

For example, a way to see the last pages like in the elderly c2 wiki would be awesome:

http://wiki.c2.com/?RecentChanges

(Anyway I'm a chronic procrastinator and probably won't be able to contribute signifcant chunks of code)

**Comment by schollz** [comment]
@hugows I think it is, mostly, finished. I liked the "recent changes" feature so I added something along those lines just now in 6d81fe5b193516241accf5f9d57a97eb4dd9ca31. You can check it out live on https://cowyo.com.

If you do have new features, I would love pull requests! Or just make an issue and I can add it in sometimes very easily (like the recent changes).

Basically whenever I feel like I personally need cowyo to do something, I put it in. I'm happy to include other things people would like, and I'm happy to maintain those changes with an exception. The one feature I'd like to avoid is having users log-in. I want to avoid this because it adds a whole new layer to maintain, it is outside my use-case, and also there are a lot of alternative wiki servers that do that (most of them do, actually!).

**Comment by hugows** [comment]
Understood, thank you!
